document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('addCattleForm');
  const tagIdInput = document.getElementById('tagId');
  const titleInput = document.getElementById('title');
  const breedSelect = document.getElementById('breed');
  const categorySelect = document.getElementById('category');
  const genderSelect = document.getElementById('gender');
  const weightInput = document.getElementById('weight');
  const ageInput = document.getElementById('age');
  const priceInput = document.getElementById('price');
  const locationInput = document.getElementById('location');
  const imageUrlInput = document.getElementById('imageUrl');
  const descriptionInput = document.getElementById('description');
  const imagePreviewBox = document.getElementById('imagePreviewBox');
  const statusAlert = document.getElementById('statusAlert');
  const statusAlertMessage = document.getElementById('statusAlertMessage');
  const submitBtn = document.getElementById('submitBtn');
  const closeAlertBtn = document.getElementById('closeAlertBtn');

  // Handle Close Alert Button
  if (closeAlertBtn) {
    closeAlertBtn.addEventListener('click', () => {
      statusAlert.classList.add('d-none');
    });
  }

  // Live Image Preview Handler
  if (imageUrlInput && imagePreviewBox) {
    imageUrlInput.addEventListener('input', () => {
      const url = imageUrlInput.value.trim();
      if (url) {
        imagePreviewBox.innerHTML = `<img src="${url}" alt="Cattle Preview" onerror="this.onerror=null; this.parentElement.innerHTML='<div class=\\'text-danger p-3 text-center\\'><i class=\\'fas fa-exclamation-triangle fa-2x mb-2\\'></i><br>Invalid image URL</div>';">`;
      } else {
        imagePreviewBox.innerHTML = `
          <i class="fas fa-camera fa-2x mb-2"></i>
          <span>Image Preview will appear here</span>
        `;
      }
    });
  }

  // Auto-generate title suggestions when Tag ID or Breed changes
  function suggestTitle() {
    if (!titleInput.value.trim() || titleInput.dataset.autoGenerated === 'true') {
      const tag = tagIdInput.value.trim();
      const breed = breedSelect.value;
      const gender = genderSelect.value;

      if (breed || tag) {
        const parts = [];
        if (breed && breed !== 'Other') parts.push(breed);
        if (gender) parts.push(gender);
        if (tag) parts.push(`#${tag}`);
        
        if (parts.length > 0) {
          titleInput.value = parts.join(' ');
          titleInput.dataset.autoGenerated = 'true';
        }
      }
    }
  }

  tagIdInput.addEventListener('input', suggestTitle);
  breedSelect.addEventListener('change', suggestTitle);
  genderSelect.addEventListener('change', suggestTitle);

  titleInput.addEventListener('input', () => {
    titleInput.dataset.autoGenerated = 'false';
  });

  // Display Status Alert Helper
  function showAlert(message, type = 'success') {
    statusAlert.className = `alert alert-${type} alert-dismissible fade show mb-4`;
    statusAlertMessage.innerHTML = message;
    statusAlert.classList.remove('d-none');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  // Form Submission
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    
    // Check HTML5 validity
    if (!form.checkValidity()) {
      e.stopPropagation();
      form.classList.add('was-validated');
      showAlert('Please fill out all required fields accurately.', 'danger');
      return;
    }

    form.classList.add('was-validated');

    const tagId = tagIdInput.value.trim();
    const title = titleInput.value.trim();
    const breed = breedSelect.value;
    const category = categorySelect.value;
    const gender = genderSelect.value;
    const weight = parseFloat(weightInput.value);
    const age = parseInt(ageInput.value, 10);
    const price = priceInput.value ? parseFloat(priceInput.value) : 0;
    const location = locationInput.value.trim() || 'Main Ranch';
    const imageUrl = imageUrlInput.value.trim() || 'https://images.pexels.com/photos/2600277/pexels-photo-2600277.jpeg';
    const description = descriptionInput.value.trim();

    // Disable button and show spinner
    submitBtn.disabled = true;
    submitBtn.innerHTML = `<span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span> Saving Record...`;

    try {
      const supabaseClient = typeof window.getSupabase === 'function' ? window.getSupabase() : null;
      const user = typeof window.getCurrentUser === 'function' ? await window.getCurrentUser() : null;
      const sellerId = user?.id || localStorage.getItem('userId') || null;
      const createdAt = new Date().toISOString();

      if (supabaseClient && supabaseClient.from) {
        const record = {
          seller_id: sellerId,
          title: title,
          breed: breed,
          category: category,
          age: age,
          weight: weight,
          price: price,
          location: location,
          image_url: imageUrl,
          description: `[Tag: ${tagId}] [Sex: ${gender}] ${description}`,
          status: 'active'
        };

        const { error } = await supabaseClient.from('cattle').insert([record]).select();
        if (error) {
          console.warn('Supabase insertion warning:', error.message);
        }
      }

      const localRecords = JSON.parse(localStorage.getItem('genostock_cattle_list') || '[]');
      localRecords.unshift({
        id: 'cattle_' + Date.now(),
        seller_id: sellerId,
        userId: sellerId,
        tagId,
        title,
        breed,
        category,
        gender,
        weight,
        age,
        price,
        location,
        imageUrl,
        description,
        status: 'active',
        createdAt,
        created_at: createdAt
      });
      localStorage.setItem('genostock_cattle_list', JSON.stringify(localRecords));
      localStorage.setItem('cattleCount', String(Number(localStorage.getItem('cattleCount') || 0) + 1));

      showAlert(
        `<i class="fas fa-check-circle me-2"></i> <strong>Success!</strong> Cattle record <strong>"${title}"</strong> registered successfully. Redirecting to dashboard...`,
        'success'
      );

      const role = (localStorage.getItem('role') || '').toLowerCase();
      const dashboard = role === 'trader' ? 'dashboard-trader.html' : 'dashboard-rancher.html';
      setTimeout(() => {
        window.location.href = dashboard;
      }, 1800);

    } catch (err) {
      console.error('Error saving cattle record:', err);
      showAlert('An unexpected error occurred while saving. Please try again.', 'danger');
      submitBtn.disabled = false;
      submitBtn.innerHTML = `<i class="fas fa-plus-circle"></i> Register Cattle Record`;
    }
  });
});
